
spring.servlet.multipart.enabled=true

# max file size - default 1MB
spring.servlet.multipart.max-file-size=50MB
# max request size - default 10MB
spring.servlet.multipart.max-request-size=100MB

server.error.include-exception=TRUE 

server.error.include-stacktrace=ALWAYS 

server.error.whitelabel.enabled=FALSE

server.servlet.session.tracking-modes=cookie

spring.devtools.livereload.enabled=true

spring.devtools.restart.enabled=true

spring.thymeleaf.cache=false

jwt.secret=c3ByaW5nU2VjdXJpdHlKd3RQcmFjdGljZUtleUphbmdKam9sa2l0

security.pwSaltKey=Va57232N709B6WO5U
